#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Author: Ahmed Tidiane BALDE
"""


COVID_19_DATA_PATH = '../../COVID-19/'
DAILY_REPORTS_PATH = COVID_19_DATA_PATH+'csse_covid_19_data/csse_covid_19_daily_reports/'
GUINEA_COVID_19_START_DATE = '03-13-2020'
